- id: '1572854591783'
  alias: Turn on light at sun set
  description: ''
  trigger:
  - event: sunset
    offset: -0:30
    platform: sun
  condition: []
  action:
  - data:
      entity_id: all
    service: light.turn_on
- id: '1572857302303'
  alias: Turn on switch in the morning
  description: ''
  trigger:
  - event: sunrise
    offset: -0:30
    platform: sun
  condition: []
  action:
  - data:
      entity_id: all
    service: switch.turn_on
- id: '1572857401579'
  alias: Turn off switch in evening
  description: ''
  trigger:
  - at: '15:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: all
    service: switch.turn_off
- id: '1572857301156'
  alias: Turn on Light when motions detected
  trigger:
  - entity_id: sensor.tradfri_motion_sensor_2
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.tradfri_bulb
      state: 'off'
    - after: 08:00:00
      before: '16:00:00'
      condition: time
  action:
  - data:
      brightness: 150
      entity_id: light.tradfri_bulb
      rgb_color:
      - 255
      - 0
      - 0
    entity_id: light.tradfri_bulb
    service: light.turn_on
  - delay: 00:00:15
  - data:
      brightness: 0
      entity_id: light.tradfri_bulb
    entity_id: light.tradfri_bulb
    service: light.turn_off
