- id: '1572854591783'
  alias: Turn on light at sun set
  description: ''
  trigger:
  - event: sunset
    offset: -00:10:00
    platform: sun
  condition: []
  action:
  - data:
      brightness: 255
      entity_id: light.tradfri_bulb
    service: light.turn_on
- id: '1572857301156'
  alias: Turn on Light when motions detected
  trigger:
  - entity_id: sensor.tradfri_motion_sensor
    platform: state
    to: 'on'
  action:
  - service: light.turn_on
    data:
      brightness: 255
      entity_id: light.tradfri_bulb
      kelvin: 2700
    entity_id: light.tradfri_bulb
  - delay: 00:00:10
  - data:
      brightness: 0
      entity_id: light.tradfri_bulb
    entity_id: light.tradfri_bulb
    service: light.turn_off
- id: '1578642959975'
  alias: Turn on warm light
  description: ''
  trigger:
  - above: 10
    below: 25
    entity_id: sensor.temp
    for: 00:00:05
    platform: numeric_state
  action:
  - data:
      color_temp: 400
      brightness: 130
      entity_id: light.tradfri_bulb
    service: light.turn_on
- id: '1578642952304'
  alias: Turn on cool light
  description: ''
  trigger:
  - above: 25
    entity_id: sensor.temp
    for: 00:00:05
    platform: numeric_state
  action:
  - data:
      color_temp: 200
      brightness: 130
      entity_id: light.tradfri_bulb
    service: light.turn_on
